export type IconsName =
  | 'eye_open'
  | 'eye_close'
  | 'home'
  | 'connections'
  | 'transactions'
  | 'profile'
  | 'logout'
  | 'Down'
  | 'Plus'
  | 'Hamburger'
  | 'Logo'
  | 'ProfileIcon'
  | 'Wallet'
  | 'FaceID'
  | 'ArrowDown'
  | 'ArrowUp'
  | 'PlusBox'
  | 'Withdraw'
  | 'Send'
  | 'Request'
  | 'GreenArrow'
  | 'RedArrow'
  | 'SuccesCheck'
  | 'sad_emoji'
  | 'logout';
export type RotateTypes = 'left' | 'right' | 'top' | 'bottom';
